version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cactro-backend
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d cactro-backend"]
      interval: 10s
      timeout: 5s
      retries: 5
